In [43]:
import numpy as np
import pandas as pd

In [44]:
data=pd.read_csv("E:\Datasets\diabetes.csv")

In [45]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [47]:
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [48]:
# rename column
data.rename(columns={"DiabetesPedigreeFunction":"DiaPredFunc"},inplace=True)

In [49]:
data.corr().round(4)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
Pregnancies         1.0000   0.1295         0.1413        -0.0817  -0.0735   
Glucose             0.1295   1.0000         0.1526         0.0573   0.3314   
BloodPressure       0.1413   0.1526         1.0000         0.2074   0.0889   
SkinThickness      -0.0817   0.0573         0.2074         1.0000   0.4368   
Insulin            -0.0735   0.3314         0.0889         0.4368   1.0000   
BMI                 0.0177   0.2211         0.2818         0.3926   0.1979   
DiaPredFunc        -0.0335   0.1373         0.0413         0.1839   0.1851   
Age                 0.5443   0.2635         0.2395        -0.1140  -0.0422   
Outcome             0.2219   0.4666         0.0651         0.0748   0.1305   

                  BMI  DiaPredFunc     Age  Outcome  
Pregnancies    0.0177      -0.0335  0.5443   0.2219  
Glucose        0.2211       0.1373  0.2635   0.4666  
BloodPressure  0.2818       0.0413  0.2395   0.0651  
SkinThickness  0.3926       0.1839 -0.1140   0.0748  
Insulin        0.1979       0.1851 -0.0422   0.1305  
BMI            1.0000       0.1406  0.0362   0.2927  
DiaPredFunc    0.1406       1.0000  0.0336   0.1738  
Age            0.0362       0.0336  1.0000   0.2384  
Outcome        0.2927       0.1738  0.2384   1.0000

In [50]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [51]:
data.Outcome.value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [52]:
# Imbalancing
from imblearn.over_sampling import SMOTE
sm=SMOTE()
x_res,y_res=sm.fit_resample(x,y)

In [53]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_data=s.fit_transform(x_res)

In [54]:
y_data=y_res

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=100)

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
l=LogisticRegression()
k=KNeighborsClassifier()
s=SVC()
r= RandomForestClassifier()  

In [72]:
print(l.fit(x_train,y_train))
print(k.fit(x_train,y_train))
print(s.fit(x_train,y_train))
print(r.fit(x_train,y_train))

LogisticRegression()
KNeighborsClassifier()
SVC()
RandomForestClassifier()


In [ ]:
y_pred=r.predict(x_test)

In [58]:
# Accuracy Score
print("Logistic Regression: ",round(l.score(x_test,y_test)*100))
print("KNN: ",round(k.score(x_test,y_test)*100))
print("SVM: ",round(s.score(x_test,y_test)*100))
print("Random Forest: ",round(r.score(x_test,y_test)*100))

Logistic Regression:  76
KNN:  80
SVM:  78
Random Forest:  84


In [59]:
# Cross Validation:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,random_state=100,shuffle=True)
skf.get_n_splits(x_data,y_data)
print(skf)
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

StratifiedKFold(n_splits=5, random_state=100, shuffle=True)


In [60]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    y_pred=cross_val_predict(r,x_test,y_test,cv=skf)
    print("Checking y_test Balancing:",Counter(y_test))
    print("Checking y_train Balancing:",Counter(y_train))
    print(scores)
    print("----------------------------------------------------------")

Checking y_test Balancing: Counter({1: 100, 0: 100})
Checking y_train Balancing: Counter({1: 400, 0: 400})
[0.775   0.84375 0.7625  0.8375  0.83125]
----------------------------------------------------------
Checking y_test Balancing: Counter({0: 100, 1: 100})
Checking y_train Balancing: Counter({1: 400, 0: 400})
[0.81875 0.83125 0.84375 0.775   0.8    ]
----------------------------------------------------------
Checking y_test Balancing: Counter({0: 100, 1: 100})
Checking y_train Balancing: Counter({1: 400, 0: 400})
[0.8625  0.76875 0.75625 0.85625 0.81875]
----------------------------------------------------------
Checking y_test Balancing: Counter({1: 100, 0: 100})
Checking y_train Balancing: Counter({1: 400, 0: 400})
[0.79375 0.81875 0.775   0.74375 0.8125 ]
----------------------------------------------------------
Checking y_test Balancing: Counter({1: 100, 0: 100})
Checking y_train Balancing: Counter({1: 400, 0: 400})
[0.825   0.8375  0.80625 0.825   0.83125]
-------------------

In [61]:
# MaxVoting Ensembel
from sklearn.ensemble import VotingClassifier
max_vote=VotingClassifier(estimators=[('Logistic Regression',l),('KNN',k),("SVM",s),('Random Forest',r)])
max_vote.fit(x_train,y_train)

VotingClassifier(estimators=[('Logistic Regression', LogisticRegression()),
                             ('KNN', KNeighborsClassifier()), ('SVM', SVC()),
                             ('Random Forest', RandomForestClassifier())])

In [62]:
max_score=max_vote.score(x_test,y_test)
max_score

0.795

In [63]:
# cross validation with ensemble
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    from sklearn.ensemble import VotingClassifier
    vote=VotingClassifier(estimators=[("Logistic",l),("KNN",k),("SVM",s)])
    vote.fit(x_train,y_train)
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    print(scores)
    print("Y data Counter: ",Counter(y_test))

[0.775   0.85    0.76875 0.83125 0.8375 ]
Y data Counter:  Counter({1: 100, 0: 100})
[0.81875 0.81875 0.81875 0.74375 0.80625]
Y data Counter:  Counter({0: 100, 1: 100})
[0.86875 0.775   0.76875 0.85    0.80625]
Y data Counter:  Counter({0: 100, 1: 100})
[0.8125  0.81875 0.79375 0.775   0.80625]
Y data Counter:  Counter({1: 100, 0: 100})
[0.83125 0.79375 0.8375  0.825   0.8375 ]
Y data Counter:  Counter({1: 100, 0: 100})


In [64]:
# bagging classifier
from sklearn.ensemble import BaggingClassifier
bg=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=14)
bg.fit(x_train,y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5,
                  random_state=14)

In [65]:
from sklearn.metrics import accuracy_score
bg_vote=bg.predict(x_test)
bg1_vote=accuracy_score(y_test,bg_vote)*100
print(bg1_vote)

78.5


In [66]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    from sklearn.ensemble import BaggingClassifier
    bg=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=14)
    bg.fit(x_train,y_train)
#     bg_vote=bg.predict(x_test)
#     print("Voting Classifier",bg_vote)
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    print(scores)
    print("Y data Counter: ",Counter(y_test))

[0.78125 0.85    0.79375 0.81875 0.84375]
Y data Counter:  Counter({1: 100, 0: 100})
[0.825   0.825   0.83125 0.78125 0.7875 ]
Y data Counter:  Counter({0: 100, 1: 100})
[0.8625  0.80625 0.75    0.84375 0.84375]
Y data Counter:  Counter({0: 100, 1: 100})
[0.80625 0.80625 0.78125 0.75625 0.8375 ]
Y data Counter:  Counter({1: 100, 0: 100})
[0.825   0.80625 0.825   0.80625 0.83125]
Y data Counter:  Counter({1: 100, 0: 100})


In [73]:
xsample=data.iloc[5:10,:-1]
ysample=data.iloc[5:10,-1]


In [81]:
y_pred=r.predict(xsample)
y_pred

C:\Users\pc\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


array([1, 1, 1, 1, 1], dtype=int64)

In [77]:
ysample

5    0
6    1
7    0
8    1
9    1
Name: Outcome, dtype: int64