In [29]:
import numpy as np
import pandas as pd

In [30]:
data=pd.read_csv(r"E:\Datasets\brain_stroke.csv")
data.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

In [31]:
data.isna().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [32]:
x=data.iloc[:,[1,2,3,7,8]]
y=data.iloc[:,-1]

age  hypertension  heart_disease  avg_glucose_level   bmi
0     67.0             0              1             228.69  36.6
1     80.0             0              1             105.92  32.5
2     49.0             0              0             171.23  34.4
3     79.0             1              0             174.12  24.0
4     81.0             0              0             186.21  29.0
...    ...           ...            ...                ...   ...
4976  41.0             0              0              70.15  29.8
4977  40.0             0              0             191.15  31.1
4978  45.0             1              0              95.02  31.8
4979  40.0             0              0              83.94  30.0
4980  80.0             1              0              83.75  29.1

[4981 rows x 5 columns]

In [33]:
from imblearn.over_sampling import SMOTE
s=SMOTE()
x_sam,y_sam=s.fit_resample(x,y)

In [34]:
# Feature Scaling by StandardScaler()
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_data=ss.fit_transform(x_sam)
x_data

array([[ 0.52623142, -0.30486946,  4.32201732,  2.02983145,  1.23926527],
       [ 1.1131273 , -0.30486946,  4.32201732, -0.21736708,  0.55406428],
       [-0.28639363, -0.30486946, -0.23137344,  0.97807591,  0.87159645],
       ...,
       [ 0.92355611, -0.30486946, -0.23137344, -0.35767468, -0.84587664],
       [ 1.06910253, -0.30486946, -0.23137344, -0.24869159,  0.67758889],
       [ 0.7853311 , -0.30486946, -0.23137344, -1.03840412,  0.13610778]])

In [35]:
y_data=y_sam

In [36]:
from collections import Counter
print(Counter(y_data))

Counter({1: 4733, 0: 4733})


In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=100)

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
l=LogisticRegression()
k=KNeighborsClassifier()
s=SVC()
r= RandomForestClassifier()  

In [39]:
print(l.fit(x_train,y_train))
print(k.fit(x_train,y_train))
print(s.fit(x_train,y_train))
print(r.fit(x_train,y_train))

LogisticRegression()
KNeighborsClassifier()
SVC()
RandomForestClassifier()


In [40]:
print("Logistic Regression: ",round(l.score(x_test,y_test)*100))
print("KNN: ",round(k.score(x_test,y_test)*100))
print("SVM: ",round(s.score(x_test,y_test)*100))
print("Random Forest: ",round(r.score(x_test,y_test)*100))

Logistic Regression:  77
KNN:  86
SVM:  79
Random Forest:  90


In [41]:
# Cross Validation:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=5,random_state=100,shuffle=True)
skf.get_n_splits(x_data,y_data)
print(skf)
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict


StratifiedKFold(n_splits=5, random_state=100, shuffle=True)


In [42]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    y_pred=cross_val_predict(r,x_test,y_test,cv=skf)
    print("Checking y_test Balancing:",Counter(y_test))
    print("Checking y_train Balancing:",Counter(y_train))
    print(scores)
    print("----------------------------------------------------------")

Checking y_test Balancing: Counter({1: 947, 0: 947})
Checking y_train Balancing: Counter({1: 3786, 0: 3786})
[0.91551155 0.92475248 0.91215324 0.90951123 0.92404227]
----------------------------------------------------------
Checking y_test Balancing: Counter({1: 947, 0: 946})
Checking y_train Balancing: Counter({0: 3787, 1: 3786})
[0.92343234 0.91485149 0.89768977 0.92404227 0.9332893 ]
----------------------------------------------------------
Checking y_test Balancing: Counter({1: 947, 0: 946})
Checking y_train Balancing: Counter({0: 3787, 1: 3786})
[0.92013201 0.92409241 0.91881188 0.91215324 0.90752972]
----------------------------------------------------------
Checking y_test Balancing: Counter({0: 947, 1: 946})
Checking y_train Balancing: Counter({1: 3787, 0: 3786})
[0.90363036 0.91683168 0.92871287 0.91413474 0.91479524]
----------------------------------------------------------
Checking y_test Balancing: Counter({0: 947, 1: 946})
Checking y_train Balancing: Counter({1: 3787, 0

### Simple Ensembel Technique

#### Max Voting

In [44]:
from sklearn.ensemble import VotingClassifier
max_vote=VotingClassifier(estimators=[('Logistic Regression',l),('KNN',k),("SVM",s),('Random Forest',r)])
max_vote.fit(x_train,y_train)

VotingClassifier(estimators=[('Logistic Regression', LogisticRegression()),
                             ('KNN', KNeighborsClassifier()), ('SVM', SVC()),
                             ('Random Forest', RandomForestClassifier())])

In [45]:
y_pred=max_vote.predict(x_test)
y_pred

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [46]:
max_score=max_vote.score(x_test,y_test)
max_score

0.8663497094558901

In [47]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    from sklearn.ensemble import VotingClassifier
    vote=VotingClassifier(estimators=[("Logistic",l),("KNN",k),("SVM",s)])
    vote.fit(x_train,y_train)
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    print(scores)
    print("Y data Counter: ",Counter(y_test))

[0.91617162 0.92673267 0.90885073 0.90554822 0.91347424]
Y data Counter:  Counter({1: 947, 0: 947})
[0.92805281 0.91353135 0.9029703  0.92668428 0.92998679]
Y data Counter:  Counter({1: 947, 0: 946})
[0.91617162 0.93069307 0.92673267 0.91413474 0.90951123]
Y data Counter:  Counter({1: 947, 0: 946})
[0.90693069 0.91353135 0.92079208 0.90951123 0.91149273]
Y data Counter:  Counter({0: 947, 1: 946})
[0.91815182 0.90561056 0.91947195 0.92602378 0.91347424]
Y data Counter:  Counter({0: 947, 1: 946})


#### Bagging Classifier

In [48]:
from sklearn.ensemble import BaggingClassifier
bg=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=14)
bg.fit(x_train,y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(), n_estimators=5,
                  random_state=14)

In [49]:
from sklearn.metrics import accuracy_score
bg_vote=bg.predict(x_test)
bg1_vote=accuracy_score(y_test,bg_vote)*100
print(bg1_vote)

90.64976228209191


In [26]:
for train_data,test_data in skf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    from sklearn.ensemble import BaggingClassifier
    bg=BaggingClassifier(base_estimator=r,n_estimators=5,random_state=14)
    bg.fit(x_train,y_train)
#     bg_vote=bg.predict(x_test)
#     print("Voting Classifier",bg_vote)
    scores=cross_val_score(r,x_train,y_train,cv=skf)
    print(scores)
    print("Y data Counter: ",Counter(y_test))

[0.92079208 0.92739274 0.91083223 0.91809775 0.91875826]
Y data Counter:  Counter({1: 947, 0: 947})
[0.92871287 0.91353135 0.90693069 0.91809775 0.91809775]
Y data Counter:  Counter({1: 947, 0: 946})
[0.90957096 0.93465347 0.92871287 0.90224571 0.91545575]
Y data Counter:  Counter({1: 947, 0: 946})
[0.92277228 0.90693069 0.92409241 0.90819022 0.92602378]
Y data Counter:  Counter({0: 947, 1: 946})
[0.92343234 0.90957096 0.92475248 0.91875826 0.91677675]
Y data Counter:  Counter({0: 947, 1: 946})
