In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("E:\Datasets\DATA.csv")

In [3]:
data.head()

Patient_ID     Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
0         P0                 None        False         True           True   
1         P1                Fever         True        False           True   
2         P2                Fever        False         True           True   
3         P3                 None         True        False          False   
4         P4  Swollen Lymph Nodes         True         True           True   

   Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
0          True            False             True          False   
1          True            False            False           True   
2         False            False            False           True   
3         False             True             True           True   
4         False            False             True           True   

   Sexually Transmitted Infection MonkeyPox  
0                           False  Negative  
1                           False  Positive  
2                           False  Positive  
3                           False  Positive  
4                           False  Positive

In [4]:
data["Systemic Illness"].unique()

array(['None', 'Fever', 'Swollen Lymph Nodes', 'Muscle Aches and Pain'],
      dtype=object)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Patient_ID                      25000 non-null  object
 1   Systemic Illness                25000 non-null  object
 2   Rectal Pain                     25000 non-null  bool  
 3   Sore Throat                     25000 non-null  bool  
 4   Penile Oedema                   25000 non-null  bool  
 5   Oral Lesions                    25000 non-null  bool  
 6   Solitary Lesion                 25000 non-null  bool  
 7   Swollen Tonsils                 25000 non-null  bool  
 8   HIV Infection                   25000 non-null  bool  
 9   Sexually Transmitted Infection  25000 non-null  bool  
 10  MonkeyPox                       25000 non-null  object
dtypes: bool(8), object(3)
memory usage: 781.4+ KB


In [6]:
data.isna().sum()

Patient_ID                        0
Systemic Illness                  0
Rectal Pain                       0
Sore Throat                       0
Penile Oedema                     0
Oral Lesions                      0
Solitary Lesion                   0
Swollen Tonsils                   0
HIV Infection                     0
Sexually Transmitted Infection    0
MonkeyPox                         0
dtype: int64

In [7]:
data.shape

(25000, 11)

## Label Encoding

In [8]:
data.columns

Index(['Patient_ID', 'Systemic Illness', 'Rectal Pain', 'Sore Throat',
       'Penile Oedema', 'Oral Lesions', 'Solitary Lesion', 'Swollen Tonsils',
       'HIV Infection', 'Sexually Transmitted Infection', 'MonkeyPox'],
      dtype='object')

In [9]:
d=data.iloc[:,1:]
cols = ['Systemic Illness', 'Rectal Pain', 'Sore Throat', 'Penile Oedema',
       'Oral Lesions', 'Solitary Lesion', 'Swollen Tonsils', 'HIV Infection',
       'Sexually Transmitted Infection', 'MonkeyPox']

In [10]:
df=data.iloc[:,1:]

In [11]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
# df['']= label_encoder.fit_transform(df['species'])
  
# df['species'].unique()
l1.fit_transform(cols)

array([9, 4, 7, 3, 2, 6, 8, 0, 5, 1], dtype=int64)

In [12]:
df[cols] = df[cols].apply(LabelEncoder().fit_transform)


In [13]:
df.head()

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  Oral Lesions  \
0                 2            0            1              1             1   
1                 0            1            0              1             1   
2                 0            0            1              1             0   
3                 2            1            0              0             0   
4                 3            1            1              1             0   

   Solitary Lesion  Swollen Tonsils  HIV Infection  \
0                0                1              0   
1                0                0              1   
2                0                0              1   
3                1                1              1   
4                0                1              1   

   Sexually Transmitted Infection  MonkeyPox  
0                               0          0  
1                               0          1  
2                               0          1  
3                               0          1  
4                               0          1

In [14]:
df.tail()

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
24995                 2            1            1              0   
24996                 0            0            1              1   
24997                 2            1            1              0   
24998                 3            0            1              0   
24999                 3            0            0              1   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
24995             1                1                0              0   
24996             0                1                1              1   
24997             0                1                1              0   
24998             1                1                1              0   
24999             0                0                1              1   

       Sexually Transmitted Infection  MonkeyPox  
24995                               1          1  
24996                               1          1  
24997                               0          1  
24998                               0          0  
24999                               0          1

In [15]:
df.corr()

Systemic Illness  Rectal Pain  Sore Throat  \
Systemic Illness                        1.000000     0.002102    -0.001614   
Rectal Pain                             0.002102     1.000000     0.006214   
Sore Throat                            -0.001614     0.006214     1.000000   
Penile Oedema                           0.006536     0.005312     0.009082   
Oral Lesions                           -0.001075     0.007747    -0.000795   
Solitary Lesion                        -0.012278     0.001147    -0.003609   
Swollen Tonsils                        -0.001018     0.002113    -0.002011   
HIV Infection                          -0.004664     0.005764     0.000771   
Sexually Transmitted Infection         -0.005868     0.000666    -0.001901   
MonkeyPox                              -0.010769     0.140727     0.063385   

                                Penile Oedema  Oral Lesions  Solitary Lesion  \
Systemic Illness                     0.006536     -0.001075        -0.012278   
Rectal Pain                          0.005312      0.007747         0.001147   
Sore Throat                          0.009082     -0.000795        -0.003609   
Penile Oedema                        1.000000      0.003850         0.002781   
Oral Lesions                         0.003850      1.000000        -0.005198   
Solitary Lesion                      0.002781     -0.005198         1.000000   
Swollen Tonsils                      0.000536     -0.007757         0.002874   
HIV Infection                        0.003620     -0.012153        -0.002335   
Sexually Transmitted Infection      -0.005722     -0.002725         0.009849   
MonkeyPox                            0.061905      0.051955         0.037471   

                                Swollen Tonsils  HIV Infection  \
Systemic Illness                      -0.001018      -0.004664   
Rectal Pain                            0.002113       0.005764   
Sore Throat                           -0.002011       0.000771   
Penile Oedema                          0.000536       0.003620   
Oral Lesions                          -0.007757      -0.012153   
Solitary Lesion                        0.002874      -0.002335   
Swollen Tonsils                        1.000000      -0.004258   
HIV Infection                         -0.004258       1.000000   
Sexually Transmitted Infection        -0.006469       0.001309   
MonkeyPox                              0.013221       0.146192   

                                Sexually Transmitted Infection  MonkeyPox  
Systemic Illness                                     -0.005868  -0.010769  
Rectal Pain                                           0.000666   0.140727  
Sore Throat                                          -0.001901   0.063385  
Penile Oedema                                        -0.005722   0.061905  
Oral Lesions                                         -0.002725   0.051955  
Solitary Lesion                                       0.009849   0.037471  
Swollen Tonsils                                      -0.006469   0.013221  
HIV Infection                                         0.001309   0.146192  
Sexually Transmitted Infection                        1.000000   0.123376  
MonkeyPox                                             0.123376   1.000000

In [16]:
df.MonkeyPox.value_counts()

1    15909
0     9091
Name: MonkeyPox, dtype: int64

## Imbalancing Technique

In [17]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [18]:
from imblearn.over_sampling import SMOTE
from collections import Counter
s=SMOTE()
x_resample,y_resample=s.fit_resample(x,y)
print(Counter(y_resample))

Counter({0: 15909, 1: 15909})


In [19]:
# from sklearn.preprocessing import StandardScaler
# ss=StandardScaler()
# ss.fit_transform(x_resample)

## Train Test Split

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_resample,y_resample,test_size=0.25,random_state=110)

In [21]:
print(Counter(y_train))

Counter({1: 12070, 0: 11793})


## Logistic Regression

In [38]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [39]:
sample1=x_test.iloc[:5,:]
sample1

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
4114                  1            0            0              0   
7518                  3            0            1              1   
8851                  3            1            1              1   
762                   0            1            1              1   
22301                 0            0            1              0   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
4114              1                1                0              1   
7518              1                0                0              0   
8851              1                1                0              0   
762               0                1                1              1   
22301             1                0                0              0   

       Sexually Transmitted Infection  
4114                                1  
7518                                0  
8851                                0  
762                                 0  
22301                               0

In [40]:
y=y_test.iloc[:5]
y


4114     1
7518     1
8851     1
762      1
22301    0
Name: MonkeyPox, dtype: int32

In [41]:
y_pred=model.predict(sample1)
y_pred

array([1, 0, 1, 1, 0])

In [45]:
sample2=x_test.iloc[6:10,:]
sample2

Systemic Illness  Rectal Pain  Sore Throat  Penile Oedema  \
13370                 3            1            1              0   
31389                 2            0            0              1   
16250                 2            0            0              1   
29481                 0            0            0              1   

       Oral Lesions  Solitary Lesion  Swollen Tonsils  HIV Infection  \
13370             0                0                0              1   
31389             0                1                1              0   
16250             0                1                1              1   
29481             1                1                1              0   

       Sexually Transmitted Infection  
13370                               1  
31389                               1  
16250                               1  
29481                               0

In [46]:
y=y_test.iloc[6:10]
y

13370    1
31389    0
16250    1
29481    0
Name: MonkeyPox, dtype: int32

In [48]:
ypred=model.predict(sample2)
ypred

array([1, 0, 1, 0])

In [49]:
y_pred=model.predict(x_test)
y_pred

array([1, 0, 1, ..., 0, 0, 0])

In [53]:
from sklearn.metrics import accuracy_score
ac1=round(accuracy_score(y_train,model.predict(x_train))*100,4)
print("Accuracy score of Training:",ac1)
ac=round(accuracy_score(y_test,model.predict(x_test))*100,4)
print("Accuracy score of Testing:",ac)


Accuracy score of Training: 61.6058
Accuracy score of Testing: 60.5908


## K Nearest Neighbors

In [57]:
from sklearn.neighbors import KNeighborsClassifier
k= KNeighborsClassifier(n_neighbors=10,metric="minkowski",p=1)
k.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10, p=1)

In [58]:
k.predict(sample1)

array([1, 1, 1, 0, 0])

In [59]:
k.predict(sample2)

array([1, 0, 0, 0])

In [62]:
from sklearn.metrics import accuracy_score
ac=round(accuracy_score(y_test,k.predict(x_test))*100,4)
print(ac)

61.7222
