In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("E:\Datasets\wine quality data.csv")

data.head()

data.info()

data.isna().sum()

data.duplicated().sum()

data.describe()

data.columns

data.quality.value_counts()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   object 
dtypes: float64(11), object(1)
memory usage: 150.0+ KB


good    855
bad     744
Name: quality, dtype: int64

In [3]:
from sklearn.preprocessing import LabelEncoder
la=LabelEncoder()
data['quality']=la.fit_transform(data['quality'])

In [4]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
# y.value_counts()

In [5]:
from imblearn.over_sampling import SMOTE
from collections import Counter
sm=SMOTE()
x_res,y_data=sm.fit_resample(x,y)
print(Counter(y_data))
# y_data.value_counts()

Counter({0: 855, 1: 855})


In [6]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_data=ss.fit_transform(x_res)

In [7]:
from sklearn.model_selection import train_test_split


x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=5)
# print(y_train.value_counts())
# print(y_test.value_counts())

In [8]:
# Use PAC
#Using Principal Dimensional Reduction
from sklearn.decomposition import PCA
pca = PCA(n_components = 4)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_
print(pd.DataFrame(explained_variance))


          0
0  0.279677
1  0.180783
2  0.141654
3  0.107549


In [9]:
print(x_test)

[[ 3.83158986  1.16916661  0.70636686  6.16974949]
 [ 3.32481286  1.12445477  3.21454342  4.53796927]
 [ 1.0566871   0.91026354  0.21700088 -0.71338487]
 ...
 [-1.0888406   0.46621799 -0.46541589  0.16142252]
 [ 1.60907485 -2.21831295  0.32284853  0.02366683]
 [ 2.63217794  2.08055338  1.02364681  3.75208787]]


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from collections import Counter
l=LogisticRegression(random_state=0)
k=KNeighborsClassifier()
s=SVC(random_state = 0, kernel = 'linear')
r= RandomForestClassifier()  

In [11]:
print(l.fit(x_train,y_train))
print(k.fit(x_train,y_train))
print(s.fit(x_train,y_train))
print(r.fit(x_train,y_train))


LogisticRegression(random_state=0)
KNeighborsClassifier()
SVC(kernel='linear', random_state=0)
RandomForestClassifier()


In [12]:
# x_sample=x_data.iloc[[5,6,7,8,1340,1131,1153,1240],:]
# y_sample=y_data.iloc[[5,6,7,8,1000,1111,1123,1245]]
# y_sample

# y_spred=k.predict(x_sample)
# print(y_spred)


In [13]:
# from sklearn.metrics import accuracy_score
# y_pred=k.predict(x_test)
# ac=accuracy_score(y_test,y_pred)*100
# print(ac)
# print(y_pred)

In [14]:
from sklearn.metrics import classification_report,confusion_matrix
for cls in (l,k,s,r):
    y_pred=cls.predict(x_test)
    cl=classification_report(y_test,y_pred)
    print(cls.__class__.__name__,'\n',(cl))
    print(confusion_matrix(y_test,y_pred))

LogisticRegression 
               precision    recall  f1-score   support

           0       0.73      0.81      0.77       185
           1       0.74      0.66      0.70       157

    accuracy                           0.74       342
   macro avg       0.74      0.73      0.73       342
weighted avg       0.74      0.74      0.73       342

[[149  36]
 [ 54 103]]
KNeighborsClassifier 
               precision    recall  f1-score   support

           0       0.72      0.74      0.73       185
           1       0.68      0.66      0.67       157

    accuracy                           0.70       342
   macro avg       0.70      0.70      0.70       342
weighted avg       0.70      0.70      0.70       342

[[137  48]
 [ 53 104]]
SVC 
               precision    recall  f1-score   support

           0       0.72      0.83      0.77       185
           1       0.75      0.62      0.68       157

    accuracy                           0.73       342
   macro avg       0.74      0.7

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score, roc_auc_score
for cls in (l,k,s,r):
    y_pred = cls.predict(x_test)
    print(
        cls.__class__.__name__,
        '\n',
        'Accuracy score: ',accuracy_score(y_test, y_pred), '\n',
        'Precision score: ',precision_score(y_test, y_pred, zero_division = 1), '\n',
        'Recall score: ',recall_score(y_test, y_pred, zero_division = 1), '\n',
        'F1 score: ',f1_score(y_test, y_pred, zero_division = 1), '\n',
        'ROC AUC score: ',roc_auc_score(y_test, y_pred), '\n', 

    )

LogisticRegression 
 Accuracy score:  0.7368421052631579 
 Precision score:  0.7410071942446043 
 Recall score:  0.6560509554140127 
 F1 score:  0.6959459459459459 
 ROC AUC score:  0.7307281804097091 

KNeighborsClassifier 
 Accuracy score:  0.7046783625730995 
 Precision score:  0.6842105263157895 
 Recall score:  0.6624203821656051 
 F1 score:  0.6731391585760518 
 ROC AUC score:  0.7014804613530727 

SVC 
 Accuracy score:  0.7309941520467836 
 Precision score:  0.751937984496124 
 Recall score:  0.6178343949044586 
 F1 score:  0.6783216783216782 
 ROC AUC score:  0.7224307109657429 

RandomForestClassifier 
 Accuracy score:  0.8157894736842105 
 Precision score:  0.8133333333333334 
 Recall score:  0.7770700636942676 
 F1 score:  0.7947882736156353 
 ROC AUC score:  0.8128593561714581 

